import './globals.css';
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Narendra Dev',
  description: 'Generated by Next.js',
  icons: [
    { rel: 'icon', url: '/favicon-32x32.png' }
  ]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon-32x32.png" sizes="any" />
      </head>
      <body>{children}</body>
    </html>
  )
}